### ISSUE TITLE
408 timeouts from Azure batch

### ISSUE THREAD

**Issue by rrrodzilla** [Azure-Samples/Cognitive-Speech-STT-ServiceLibrary#10]
Hi,

Really hope someone has an answer for this.  Our code is in a console app, (it's pretty much the code in this sample) that transcribes a single file and receives responses and then writes the responses to a text file.  Works great locally on our machines.

However, when we add that console app as a resource to a node on Azure batch and spin up multiple nodes (or even a single one) it makes the initial transcribe request and then it sits and times out with a request 408 timeout error.  

The nodes are vm images of Windows Server 2008R2 and I've verified the requisite ports are open as we are able to call other services.

Please tell me there's a setting or something we need to make in order to make this work.

Best Regards,

Roland

**Comment by amrmahdi** [comment]
Can you paste the stack trace ?

**Comment by rrrodzilla** [comment]
Stack trace below, as mentioned, this code executes just fine when run locally:

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (408) Request Timeout.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bing.Messaging.WebSocketFactory.<CreateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bing.Messaging.RxTx.<ConnectAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bing.Messaging.MessagingComponentFactory.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bing.Speech.SpeechClient.AudioConnection.<ConnectAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Bing.Speech.SpeechClient.AudioConnection.<ConnectAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bing.Speech.SpeechClient.<StreamAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bing.Speech.SpeechClient.<RecognizeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UCI.DirtyBlobRename.TranscribeBlobCommand.<RunTranscriber>d__19.MoveNext() in C:\Users\RolandRodriguez\source\repos\UCI.DirtyBlobRename\UCI.DirtyBlobRename\TranscribeBlobCommand.cs:line 248
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at UCI.DirtyBlobRename.TranscribeBlobCommand.Run(String[] remainingArguments) in C:\Users\RolandRodriguez\source\repos\UCI.DirtyBlobRename\UCI.DirtyBlobRename\TranscribeBlobCommand.cs:line 132
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage) in c:\code\ManyConsole\ManyConsole\ConsoleCommandDispatcher.cs:line 82
   at UCI.DirtyBlobRename.Program.Main(String[] args) in C:\Users\RolandRodriguez\source\repos\UCI.DirtyBlobRename\UCI.DirtyBlobRename\Program.cs:line 14

**Comment by amrmahdi** [comment]
The .NET ClientWebsocket implementation was not yet supported on Windows Server 2008. Upgrading your OS version should resolve the issue.
